### PR TITLE
Support ActiveRecord 6

### LINKED ISSUE #175: Rails 6 support
Given I update to rails 6 in my Gemfile:
```diff
diff --git a/Gemfile b/Gemfile
 
-gem 'rails', '~>5.2'
+gem 'rails', '~>6.0.0.beta2'

```

Then I will not be able to update to Rails 6 due to a limit in crypt_keeper. Error message (when running `bundle update rails`:

```
    crypt_keeper (~> 2.0.0.rc2) was resolved to 2.0.1, which depends on
      activesupport (< 5.3, >= 4.2)

    rails (~> 6.0.0.beta2) was resolved to 6.0.0.beta2, which depends on
      activesupport (= 6.0.0.beta2)
```

What are the plans to update this plugin and maintaining the releases?

### PR DESCRIPTION
**Pull request by kevin-j-m**
### Support ActiveRecord 6
This updates the gemspec to support activerecord version 6.0.0 and
updates the Appraisals file to include testing against activerecord
6.0.0.

Rails 6 requires ruby version 2.5.0 or higher, so lower versions of
ruby have been excluded from the build matrix.

### Remove SchemaMigration descendents from spec deletion
The `spec_helper.rb` file includes an after hook that runs on each spec
which takes every descendant of `ActiveRecord::Base` and calls
`delete_all` on it.

In ActiveRecord 6, there are two classes that are returned as
descendants that were not previously:

* ActiveRecord::SchemaMigration
* primary::SchemaMigration

Calling `delete_all` on these models causes issues with the test suite
because those tables do not exist when running this test suite. As such,
this removes those classes from descendants that we should delete all
the records from after each test is run.

As such, this modifies that after hook to exclude any descendant whose
class name includes `SchemaMigration`.

This may be a bit of a cat-and-mouse game with activerecord internals,
but as long as we want to have the spec_helper delete every record from
every class that exists in the test system in this manner, I think we
need to have this list of excluded classes.

This should not have an impact on prior versions of activerecord, as
these classes were not previously descendants, so removing a thing that
doesn't exist won't have a functional impact. It does have a negative
performance affect on the test suite, as it needs to run through the
descendants with every spec run and see if any of them are a
`SchemaMigration` and remove them.

This builds on the work in #178.

Fixes #175.

### CODE REVIEW

**Comment by kevin-j-m** [comment]
The second commit 16375077ec758122f60e11d0ab985c9072ee4585 here is one possible way we can get around the test suite issues that we're seeing in Rails 6.

However, getting past those introduced a new problem which I attempted (unsuccessfully) to address in the third (852cca4769629626176d5c57f1b71607f204fa1a) and fourth (471f626d9e779828e40faf117a088241d0f1546f) commit in different ways.

After removing any `SchemaMigration` table records for deletion in tests, the [test suite](https://travis-ci.org/jmazzi/crypt_keeper/builds/617519783?utm_medium=notification&utm_source=github_status) was having an issue when testing in ActiveRecord 6 where it was looking for sqlite 3 ~> 1.4.

I then attempted (852cca4769629626176d5c57f1b71607f204fa1a) to specify using sqlite version 1.4 in AR 6, and retain sqlite version 1.3 in all other versions. That introduced issues in the [test suite](https://travis-ci.org/jmazzi/crypt_keeper/builds/617522538?utm_source=github_status&utm_medium=notification) only on AR 4.2.

I then checked if I could uniformly use sqlite version 1.4 across all versions (471f626d9e779828e40faf117a088241d0f1546f) and running the [test suite](https://travis-ci.org/jmazzi/crypt_keeper/builds/617525268?utm_medium=notification&utm_source=github_status) again yielded the same results as the prior change - AR 4.2 isn't happy, other versions of AR are satisfied.

I could use some help with some combination of [Appraisal](https://github.com/thoughtbot/appraisal), Travis, sqlite, or ActiveRecord knowledge to move this forward.

**Comment by kevin-j-m** [comment]
@jmazzi is the change in 16375077ec758122f60e11d0ab985c9072ee4585 something that's acceptable? I'm wondering if this is worth moving forward on, or if we should evaluate different approaches.

**Comment by kevin-j-m** [comment]
This is very, very much not my call, but with the release of Rails 6, I believe 4.2 falls outside of Rails' [maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html). 

That doesn't mean that crypt_keeper can't keep supporting compatibility with 4.2, but that may be a larger/separate conversation on what level of support and compatibility across versions this gem wants to continue ensuring.

I also don't think my inability in an evening to get the test matrix for the 4.2 tests for a particular version of sqlite3 means this should drop support for 4.2 entirely. It just means I need help getting us there.

**Comment by kevin-j-m** [comment]
4.2 [requires](https://github.com/rails/rails/blob/4-2-stable/Gemfile#L104) ~> 1.3.6
5.2 [allows](https://github.com/rails/rails/blob/5-2-stable/Gemfile#L139) >= 1.3.6, as of https://github.com/rails/rails/pull/35154
6.0 [requires](https://github.com/rails/rails/blob/6-0-stable/Gemfile#L123) ~> 1.4

So, that explains to me why my fourth commit isn't working, but isn't clear why the third isn't, which had the appraisal file specify the version of sqlite3 as 1.3 for everything that's not 6.0, and 1.4 for 6.0.

Does appraisal do something different for development dependencies? Am I misunderstanding or misusing appraisal to be able to set this from AR version to AR version?

**Comment by kevin-j-m** [comment]
I was screwing up the use of the `~>` operator last night. My last commit fixes this, and CI is now green across the full test matrix.

**Comment by kevin-j-m** [comment]
@jmazzi I know it's a busy time of the year for most with both personal and professional obligations, but please let me know if and how I can help move this forward. And thanks for providing & maintaining this library!

**Comment by kevin-j-m** [comment]
Happy New Year, @jmazzi! Any feedback you may have to make progress on this would be greatly appreciated.

**Comment by danielricecodes** [comment]
Please merge this.  Thank you.

**Comment by rajdeepbhatia** [comment]
Please merge this already!

**Comment by thilonel** [comment]
@jmazzi this is blocking us from updating to Rails 6. Could you please merge it?

**Comment by jmazzi** [comment]
This has been released as `2.1.0`

**Comment by jesperronn** [comment]
Thanks a lot for the release. Much anticipated! 👍👍💪🎉

**Comment by danielricecodes** [comment]
Thank you @jmazzi.  One request: Given the time this took to release, I would strongly suggest moving this gem into its own organization and allowing more than one maintainer.  Merging, reviewing, and cutting a gem is something the community can easily do!

**Pull request merged**
