### PR TITLE
Allows rails 7 with minor versions

### PR DESCRIPTION
**Pull request by aYaremchuk**
Rails 7.1.3 incompatible

```
Could not find compatible versions

Because every version of crypt_keeper depends on activerecord >= 7.0.0, < 7.1.A
  and rails >= 7.1.3 depends on activerecord = 7.1.3,
  every version of crypt_keeper is incompatible with rails >= 7.1.3.
So, because Gemfile depends on rails = 7.1.3
  and Gemfile depends on crypt_keeper >= 0,
  version solving has failed.
```
Added minor change to support minor versions of rails 7
Also changed path version of gem

### CODE REVIEW

**Comment by jmazzi** [comment]
@aYaremchuk the tests are failing

**Comment by jmazzi** [comment]
@Capncavedan @aYaremchuk tests are still failing as of today; please consider investigating this if you would like to see a gem cut for this version.

**Comment by johan-smits** [comment]
@jmazzi looking at the changes it would suspect to fail only for the `7.1` rails versions. But all tests fail also the previous ones. Could it be that also the main branch fails recently?

**Comment by aYaremchuk** [comment]
There is an issue with public/private keys. 
These keys do not have an expiration date, but tests fail even with minor changes.

It appears this issue was resolved in the following pull request: [203](https://github.com/jmazzi/crypt_keeper/pull/203).

**Comment by aYaremchuk** [comment]
Closing this PR.

It seems the issue with the broken tests was resolved in this pull request: [link](https://github.com/jmazzi/crypt_keeper/pull/203).

**Pull request closed without merging**
