### PR TITLE
Add support of PostgreSQL's Raw Encryption

### PR DESCRIPTION
**Pull request by aquajach**
**Why PostgreSQL's Raw Encryption?**

Although in the PostgreSQL's documentation the raw encryption is said as less recommended than pgp, it has its own advantages. In database encryption, flexibility and security are two sides on a balance. If a project with PostgreSQL requires both encryption and quick search function, the raw encryption seems the only choice. Searching in pgp from 1,000 records brings a major performance issue. 

I love PostgreSQL and crypt_keeper (esp. its simplicity) to do encryption, and don't want to give up any of them.

### CODE REVIEW

**Comment by itspriddle** [comment]
Hey @aquajach, thanks for the PR :+1:, just a couple small things:

1. I've just added an option to silence log output in #121. Can you add `return if CryptKeeper.silence_logs? && payload =~ filter` to L18 of `lib/crypt_keeper/log_subscriber/postgres_raw.rb` and a spec to `spec/log_subscriber/postgres_pg_raw_spec.rb` to verify that behavior? An example of the spec for existing log subscribers is in #121 

2. The Travis CI build is failing due to appraisal. Can you pull master, rebase your branch, and then run `bundle exec appraisal` and check in the gemfiles generated under `gemfiles/`?

Thanks again!

**Comment by aquajach** [comment]
@itspriddle Just updated accordingly and the build is restored

**Comment by itspriddle** [comment]
👍

@jmazzi any thoughts?

**Comment by jmazzi** [comment]
@aquajach @itspriddle wow, somehow missed this PR a while ago. I'm ok with it if there's still interest here.

**Comment by itspriddle** [comment]
@jmazzi I will defer to @aquajach. It's not something we use or I've seen requested outside of this PR. I'd be fine adding it as long as there is some usage in the wild. 

@aquajach if you're still keen to see this added, please let us know. If you can speak to any issues you may have come across using it that would be especially helpful!

**Comment by itspriddle** [comment]
Closing – please feel free to reopen if this is something you are still looking to see added. Thanks!

**Pull request closed without merging**
