### PR TITLE
rails 6 deps updated

### PR DESCRIPTION
**Pull request by fabriziospadaro**
Attempting to fix #178 to work with rails 6.0

### CODE REVIEW

**Comment by jmazzi** [comment]
@fabriziospadaro can you send up another commit to trigger the Travis build? It didn't run on PR creation.

**Comment by taylorwilliams** [comment]
@jmazzi I suspect this PR will have the same issues https://github.com/jmazzi/crypt_keeper/pull/178 had. Looking like it needs some support from yourself.

**Comment by chevinbrown** [comment]
👀

**Comment by jmazzi** [comment]
Closed by #184

**Pull request closed without merging**
