### PR TITLE
add decrypt table (the reverse of encrypt table)

### PR DESCRIPTION
**Pull request by serixscorpio**
This is a functionality I found useful.  This is used as a reverse step of encrypt_table! in the context of calling in within a migration.  The decrypt_table! method allows one to rollback the migration.

### CODE REVIEW

**Comment by acrogenesis** [comment]
any update on this merge? @jmazzi @serixscorpio

**Comment by jmazzi** [comment]
@serixscorpio @dankohn @acrogenesis this PR needs a rebase and then I can merge.

**Comment by serixscorpio** [comment]
Also, I noticed the crypt_keeper version in various gemfile.lock used by travis ci need to be updated from 0.18.4 to 0.19.0.  7ff84be

**Comment by jmazzi** [comment]
@serixscorpio you need to run `bundle exec appraisal install`. That will update the files

**Comment by serixscorpio** [comment]
I see.  Thanks! Appraisal works great! I'm curious, what's the rationale behind keeping the different gemfile.lock in version control?

**Comment by jmazzi** [comment]
@serixscorpio oversight :) - opened #97

**Pull request merged**
